### ISSUE TITLE
Create Drawsql Diagram, show snapshot in the readme and also in the resources section insert link for Drawsql Diagram

### ISSUE THREAD

**Issue by giunashvili** [RedberryInternship/nanuka-laravel-8-from-scratch#1]

**Comment by naa15** [comment]
@giunashvili I added it in the readme.md but which resources section do you mean? Should I add it as a support.md file?

**Comment by giunashvili** [comment]
No, in the readme you have several sections like "Introduction", "Getting Started" and so on.

Just add Resources section and under that insert the Drasql Diagram link

**Comment by naa15** [comment]
oh okay :ok_hand:
