### ISSUE TITLE
Extract this styles into resources/css

### ISSUE THREAD

**Issue by giunashvili** [RedberryInternship/nanuka-laravel-8-from-scratch#22]
https://github.com/RedberryInternship/nanuka-laravel-8-from-scratch/blob/50eb7975b6defa8a5db42f04fc01a44c0ba369b7/resources/views/layout.blade.php#L11-L16

**Comment by giunashvili** [comment]
@naa15 

I said extract them not remove entirely ))

**Comment by naa15** [comment]
It's not removed :D I moved it to app.css file

**Comment by giunashvili** [comment]
@naa15 
There is nothing in the resouces/css/app.css
