### ISSUE TITLE
Some of the files needs formatting with CS Fixer, arnt you using it? here for example there are unused imports, and other placeses array declarations and stuff like that please go through with your PHP files and fix them with PHP CS FIxer

### ISSUE THREAD

**Issue by giunashvili** [RedberryInternship/nanuka-laravel-8-from-scratch#24]
https://github.com/RedberryInternship/nanuka-laravel-8-from-scratch/blob/50eb7975b6defa8a5db42f04fc01a44c0ba369b7/app/Http/Controllers/PostController.php#L1-L10

**Comment by naa15** [comment]
I'm using cs-fixer but it doesn't delete unused imports, I dunno why :woman_shrugging:

**Comment by giunashvili** [comment]
Is your configuration file set correctly?

**Comment by naa15** [comment]
I think so :woman_shrugging:
