### ISSUE TITLE
Dont need this comment

### ISSUE THREAD

**Issue by giunashvili** [RedberryInternship/nanuka-laravel-8-from-scratch#3]
https://github.com/RedberryInternship/nanuka-laravel-8-from-scratch/blob/50eb7975b6defa8a5db42f04fc01a44c0ba369b7/routes/web.php#L35-L36

**Comment by naa15** [comment]
Since this project is only for practice, I decided to keep these comments in case I'll ever need to use them to remember some stuff. So I'm not deleting some of those.

**Comment by giunashvili** [comment]
@naa15 Okay
